# Site settings
name: Я Анвархон,сетевой администратор
title: Я Анвархон,сетевой администратор
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://bchiang7.github.io/
baseurl: ''
email: brittany.chiang@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shutterstock.com%2Fimage-vector%2Fak-logo-design-monogram-initials-icon-2239618763&psig=AOvVaw3RI9s4h3PIKPDQziPeSBsk&ust=1703570287063000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMCS3oL0qYMDFQAAAAAdAAAAABAD
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:afenix950@gmail.com
  - title: instagram
    url: https://www.instagram.com/anvarkhan.fakhriddinov/
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100078992947763&sk=friends
  - title: linkedin
    url: https://www.linkedin.com/in/anvarkhon-fakhriddinov-758b46258/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
